# cSpell: disable

language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
dist: xenial
sudo: required
services:
  - postgresql
  - redis-server
before_install:
  - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.2-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.3.2-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
before_script:
  - psql -c 'create database protean_test;' -U postgres
  - sleep 10
python:
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
matrix:
  include:
    - name: "lint"
        python: 3.7
        env:
          - TEST_CMD="pre-commit run --all-files"
  allow_failures:
    - python: 3.8-dev
install:
  - pip install .[test]
script:
  - pytest --slow --postgresql --elasticsearch --redis --cov=protean --cov-config .coveragerc tests
after_success:
  - pip install codecov
  - codecov
