# cSpell: disable

language: python
os:
  - linux
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
dist: xenial
services:
  - postgresql
  - redis
before_install:
  - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.2-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.3.2-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
before_script:
  - psql -c 'create database protean_test;' -U postgres
  - sleep 10
install:
  - pip install codecov pre-commit
  - pip install .[test]
jobs:
  include:
    - name: "lint"
      python: 3.7
      env:
        - TEST_CMD="pre-commit run --all-files"
    - name: "3.7"
      python: 3.7
    - name: "3.8"
      python: 3.8
    - name: "3.8-dev"
      python: 3.8-dev
    - name: "3.9-dev"
      python: 3.9-dev
  allow_failures:
    - python: 3.9-dev
script:
  - pytest --slow --sqlite --postgresql --elasticsearch --redis --cov=protean --cov-config .coveragerc tests
after_success:
  - codecov
notifications:
  on_success: change
  on_failure: always
