site_name: Protean
site_url: https://docs.proteanhq.com
repo_name: proteanhq/protean
repo_url: https://github.com/proteanhq/protean
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - mdx_include
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      check_paths: true
      base_path: docs_src
nav:
  - Protean:
    - index.md
    - intro/philosophy.md
    - intro/whitepaper.md
    - intro/features.md
  - Core Concepts:
    # - core-concepts/index.md
    - core-concepts/analysis-model.md
    # - core-concepts/identity.md
    # - Domain-Driven Design:
    #   - core-concepts/domain-driven-design/index.md
    #   - core-concepts/domain-driven-design/ubiquitous-language.md
    #   - core-concepts/domain-driven-design/bounded-contexts.md
    #   - core-concepts/domain-driven-design/contexts-and-subdomains.md
    #   - core-concepts/domain-driven-design/strategic-design.md
    #   - core-concepts/domain-driven-design/tactical-design.md
    - Building Blocks:
      - core-concepts/building-blocks/index.md
    #   - core-concepts/building-blocks/aggregates.md
    #   - core-concepts/building-blocks/entities.md
    #   - core-concepts/building-blocks/value-objects.md
    #   - core-concepts/building-blocks/domain-services.md
    #   - core-concepts/building-blocks/commands.md
    #   - core-concepts/building-blocks/command-handlers.md
    #   - core-concepts/building-blocks/events.md
    #   - core-concepts/building-blocks/event-handlers.md
    #   - core-concepts/building-blocks/repositories.md
    #   - core-concepts/building-blocks/models.md
    #   - core-concepts/building-blocks/view-models.md
    # - Command-Query Responsibility Segregation:
    #   - core-concepts/command-query-responsibility-segregation/index.md
    #   - core-concepts/command-query-responsibility-segregation/commands.md
    #   - core-concepts/command-query-responsibility-segregation/queries.md
    #   - core-concepts/command-query-responsibility-segregation/events.md
    # - Event Sourcing:
    #   - core-concepts/event-sourcing/index.md
    #   - core-concepts/event-sourcing/events.md
    #   - core-concepts/event-sourcing/snapshots.md
    #   - core-concepts/event-sourcing/projections.md
  - Guides:
    - guides/index.md
    - guides/getting-started/start-here.md
    - guides/getting-started/installation.md
    #  - guides/getting-started/quickstart.md
    - Compose a Domain:
      - guides/compose-a-domain/index.md
      - guides/compose-a-domain/domain-object.md
      - guides/compose-a-domain/register-elements.md
      - guides/compose-a-domain/initialize-domain.md
      - guides/compose-a-domain/activate-domain.md
      - guides/compose-a-domain/when-to-compose.md
      - guides/compose-a-domain/element-decorators.md
      - guides/compose-a-domain/object-model.md
      - guides/compose-a-domain/configuration.md
      - guides/compose-a-domain/identity.md
    - Defining Concepts:
      - guides/domain-definition/index.md
      - Fields:
        - guides/domain-definition/fields/index.md
        - guides/domain-definition/fields/options.md
        - guides/domain-definition/fields/simple-fields.md
        - guides/domain-definition/fields/container-fields.md
        - guides/domain-definition/fields/association-fields.md
      - guides/domain-definition/aggregates.md
      - guides/domain-definition/entities.md
      - guides/domain-definition/value-objects.md
      - guides/domain-definition/events.md
      - guides/domain-definition/repositories.md
    - Adding Behavior:
      - guides/domain-behavior/index.md
      - guides/domain-behavior/validations.md
      - guides/domain-behavior/invariants.md
      - guides/domain-behavior/aggregate-mutation.md
      - guides/domain-behavior/raising-events.md
      - guides/domain-behavior/domain-services.md
    - Changing State:
      - guides/change-state/index.md
      - guides/change-state/commands.md
      - guides/change-state/command-handlers.md
      - guides/change-state/persist-aggregates.md
      - guides/change-state/unit-of-work.md
      - guides/change-state/retrieve-aggregates.md
    - Propagating State:
      - guides/propagate-state/index.md
      - guides/propagate-state/event-handlers.md
    #   - guides/propagate-state/events-across-contexts.md
    #   - guides/propagate-state/views.md
    # - Application Layer:
    #   - guides/app-layer/index.md
    #   - guides/app-layer/application-services.md
    #   - guides/domain-definition/subscribers.md
    # - Infrastructure:
    #   - guides/app-layer/index.md (ports-and-adapters)
    #   - guides/app-layer/persisting-data.md (unit-of-work)
    #   - guides/app-layer/views.md
    #   - guides/app-layer/providers.md
    #   - guides/app-layer/models.md
    #   - guides/app-layer/brokers.md
    #   - guides/app-layer/caches.md
    #   - guides/app-layer/event-stores.md
    # - Adapters (Port Definition):
    #   - guides/adapters/index.md
    #   - guides/adapters/database.md
    #   - guides/adapters/message-brokers.md
    #   - guides/adapters/caches.md
    #   - guides/adapters/event-stores.md
    # - CQRS:
    #   - guides/command-handling/index.md (flow)
    #   - guides/command-handling/commands.md
    #   - guides/command-handling/command-handlers.md
    #   - guides/event-handling/event-handlers.md
    # - Event Sourcing:
    #   - guides/event-sourcing/index.md
    #   - guides/event-sourcing/event-sourced-aggregates.md
    #   - guides/event-sourcing/snapshots.md
    #   - guides/event-sourcing/projections.md
    #   - guides/event-sourcing/flow.md
    # - Testing:
    #   - guides/testing/index.md (100% testability)
    #   - guides/testing/unit-testing.md
    #   - guides/testing/integration-testing.md
    #   - guides/testing/functional-testing.md
    #   - guides/testing/acceptance-testing.md
    - Command Line Interface:
      - guides/cli/index.md
      - guides/cli/discovery.md
      - guides/cli/new.md
      - guides/cli/shell.md
      - guides/cli/docs.md
      - guides/cli/test.md
  # - Advanced:
  #   - advanced/index.md
  #   - advanced/multi-domain.md
  #   - advanced/escape-hatches.md
  #   - advanced/security.md
  #   - advanced/performance.md
  #   - advanced/monitoring.md
  #   - advanced/integration.md
  #   - advanced/troubleshooting.md
  # - API:
  #   - api/index.md
  # - Examples:
  #   - examples/index.md
  #   - examples/quickstart.md
  # - faq.md
  - glossary.md
  # - changelog.md
  - Community: 
    - community/index.md
    - community/contributing.md