[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "protean"
version = "0.13.1"
description = "Protean Application Framework"
authors = ["Subhash Bhushan C <subhash@team8solutions.com>"]
license = "BSD 3-Clause"
readme = "README.md"
repository = "https://github.com/proteanhq/protean"
documentation = "https://protean.readthedocs.io/en/latest/"
keywords = [
    "ddd",
    "domain-driven-design",
    "clean-architecture",
    "hexagonal-architecture",
    "onion-architecture",
    "microservices",
    "python-framework",
    "repository-pattern",
    "cqrs",
    "event-sourcing",
    "aggregates",
    "entities",
    "value-objects",
    "services",
    "bounded-contexts",
    "asynchronous",
    "event-driven-architecture",
    "cqrs-framework",
    "event-sourcing-framework"
]
classifiers=[
    # complete classifier list: http://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.11"
bleach = ">=4.1.0"
copier = "^9.1.1"
inflection = ">=0.5.1"
ipython = "^8.23.0"
marshmallow = ">=3.15.0"  # FIXME Remove core dependency
python-dateutil = ">=2.8.2"
typer = ">=0.12.3"
werkzeug = ">=2.0.0"

##########
# Extras *
##########

elasticsearch = {version = "~7.17.9", optional = true}
elasticsearch-dsl = {version = "~7.4.1", optional = true}
redis = {version = "~5.0.7", optional = true}
sqlalchemy = {version = "~2.0.30", optional = true}
psycopg2 = {version = ">=2.9.9", optional = true}
flask = {version = ">=1.1.1", optional = true}
sendgrid = {version = ">=6.1.3", optional = true}
message-db-py = {version = ">=0.2.0", optional = true}

[tool.poetry.extras]
elasticsearch = ["elasticsearch", "elasticsearch-dsl"]
redis = ["redis"]
postgresql = ["sqlalchemy", "psycopg2"]
sqlite = ["sqlalchemy"]
message-db = ["message-db-py"]
flask = ["flask"]
sendgrid = ["sendgrid"]

############################
# Development Dependencies *
############################

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
check-manifest = ">=0.49"
coverage = ">=7.3.2"
docutils = ">=0.20.1"
pre-commit = ">=2.16.0"
ruff = "^0.4.3"
twine = ">=4.0.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
mock = "5.1.0"
pytest-asyncio = ">=0.21.1"
pytest-cov = ">=4.1.0"
pytest-mock = "3.12.0"
pytest = "^8.2.1"
mypy = "^1.11.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.5.15"
mdx-include = "^1.4.2"

[tool.poetry.group.types]
optional = true

[tool.poetry.group.types.dependencies]
types-mock = ">=0.1.3"
types-python-dateutil = ">=0.1.6"
types-redis = ">=3.5.4"
types-Werkzeug = ">=1.0.5"

[tool.poetry.scripts]
protean = "protean.cli:app"

##################
# Configurations #
##################

[tool.ruff.lint.isort]
known-first-party = ["protean"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
filterwarnings = [
    "ignore::sqlalchemy.exc.SAWarning",
    "ignore::sqlalchemy.exc.SADeprecationWarning"
]
python_files = [
    "test_*.py",
    "*_test.py",
    "tests.py"
]
addopts = "-ra --strict-markers --doctest-modules --doctest-glob=*.rst --tb=short"
markers = [
    "slow",
    "pending",
    "sqlite",
    "postgresql",
    "elasticsearch",
    "redis",
    "message_db",
    "sendgrid",
    "database",
    "broker_common",
    "eventstore",
    "no_test_domain",
]

[tool.mypy]
exclude = [".venv", "src/protean/template", "docs_src"]